In [1]:
import numpy as np

# Create a 5x5 matrix with random integers (0–9)
input_matrix = np.random.randint(0, 10, (5, 5))

print("Input Matrix:\n")
print(input_matrix)

# Define a 3x3 kernel
kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

print("\nKernel:\n")
print(kernel)

# Output activation map (5-3+1 = 3)
output = np.zeros((3, 3))

# Manual Convolution
for i in range(3):
    for j in range(3):
        region = input_matrix[i:i+3, j:j+3]
        output[i, j] = np.sum(region * kernel)

print("\nActivation Map:\n")
print(output)

Input Matrix:

[[1 6 9 7 1]
 [7 7 3 4 5]
 [4 7 9 5 6]
 [3 1 7 4 6]
 [5 9 2 0 0]]

Kernel:

[[ 1  0 -1]
 [ 1  0 -1]
 [ 1  0 -1]]

Activation Map:

[[-9.  4.  9.]
 [-5.  2.  2.]
 [-6.  8.  6.]]


In [2]:
import numpy as np

def apply_stride_convolution(input_matrix, kernel, stride):

    input_size = input_matrix.shape[0]
    kernel_size = kernel.shape[0]

    output_size = ((input_size - kernel_size) // stride) + 1

    output = np.zeros((output_size, output_size))

    for i in range(0, input_size - kernel_size + 1, stride):
        for j in range(0, input_size - kernel_size + 1, stride):

            region = input_matrix[i:i+kernel_size, j:j+kernel_size]

            output[i//stride, j//stride] = np.sum(region * kernel)

    return output

# Example
matrix = np.random.randint(0, 10, (6,6))

kernel = np.array([
    [1,0,-1],
    [1,0,-1],
    [1,0,-1]
])

print("Input Matrix:\n")
print(matrix)

print("\nActivation Map (Stride = 2):\n")
print(apply_stride_convolution(matrix, kernel, stride=2))

Input Matrix:

[[0 9 2 8 5 1]
 [8 4 7 8 8 9]
 [7 0 1 6 3 0]
 [8 1 3 0 5 2]
 [8 0 1 3 8 5]
 [4 5 3 1 5 5]]

Activation Map (Stride = 2):

[[  5.  -6.]
 [ 18. -11.]]


In [3]:
import numpy as np

# Create random matrix
input_matrix = np.random.randint(0,10,(5,5))

kernel = np.array([
    [1,0,-1],
    [1,0,-1],
    [1,0,-1]
])

# Add Zero Padding
padded = np.pad(input_matrix, pad_width=1, mode='constant')

print("Original Matrix:\n")
print(input_matrix)

print("\nPadded Matrix:\n")
print(padded)

output = np.zeros((5,5))

for i in range(5):
    for j in range(5):

        region = padded[i:i+3, j:j+3]

        output[i,j] = np.sum(region * kernel)

print("\nActivation Map with Padding:\n")
print(output)

Original Matrix:

[[3 2 2 9 9]
 [9 4 9 4 7]
 [2 3 6 5 2]
 [0 2 5 6 7]
 [0 5 4 2 2]]

Padded Matrix:

[[0 0 0 0 0 0 0]
 [0 3 2 2 9 9 0]
 [0 9 4 9 4 7 0]
 [0 2 3 6 5 2 0]
 [0 0 2 5 6 7 0]
 [0 0 5 4 2 2 0]
 [0 0 0 0 0 0 0]]

Activation Map with Padding:

[[ -6.   1.  -7.  -5.  13.]
 [ -9.  -3.  -9.  -1.  18.]
 [ -9.  -9.  -6.   4.  15.]
 [-10. -13.  -3.   4.  13.]
 [ -7.  -9.  -1.   0.   8.]]


In [4]:
import numpy as np

matrix = np.random.randint(0,10,(5,5))

print("Input Matrix:\n")
print(matrix)

# Edge Detection Kernel (Sobel-like)
edge_kernel = np.array([
    [-1,0,1],
    [-2,0,2],
    [-1,0,1]
])

# Blur Kernel
blur_kernel = np.ones((3,3))/9

edge_output = np.zeros((3,3))
blur_output = np.zeros((3,3))

for i in range(3):
    for j in range(3):

        region = matrix[i:i+3, j:j+3]

        edge_output[i,j] = np.sum(region * edge_kernel)

        blur_output[i,j] = np.sum(region * blur_kernel)

print("\nEdge Detection Output:\n")
print(edge_output)

print("\nBlur Output:\n")
print(blur_output)

Input Matrix:

[[1 1 6 8 9]
 [7 8 3 2 2]
 [5 1 2 4 9]
 [6 2 0 8 2]
 [7 6 0 0 4]]

Edge Detection Output:

[[ -6.  -2.   8.]
 [-16.   6.  15.]
 [-22.   9.  15.]]

Blur Output:

[[3.77777778 3.88888889 5.        ]
 [3.77777778 3.33333333 3.55555556]
 [3.22222222 2.55555556 3.22222222]]


In [ ]:
from PIL import Image
import numpy as np

# Load image
image = Image.open("Instagram.jpg")

# Convert to grayscale
gray = image.convert("L")

# Resize to 8x8
gray = gray.resize((8,8))

# Convert to NumPy array
image_array = np.array(gray)

print("Input Array:\n")
print(image_array)

# Custom Edge Detection Filter
kernel = np.array([
    [1,0,-1],
    [1,0,-1],
    [1,0,-1]
])

output = np.zeros((6,6))

for i in range(6):
    for j in range(6):

        region = image_array[i:i+3, j:j+3]

        output[i,j] = np.sum(region * kernel)

print("\nOutput Array:\n")
print(output)

print("\nObservation:")
print("The custom filter highlights vertical edges in the image by detecting sudden changes in pixel intensity.")