In [1]:
import numpy as np

# Create a 6x6 random grayscale image
image = np.random.randint(0, 256, (6, 6))

print("Original Image:\n")
print(image)

# 2x2 Max Pooling with Stride 2
pooled = np.zeros((3, 3), dtype=int)

for i in range(0, 6, 2):
    for j in range(0, 6, 2):
        pooled[i//2, j//2] = np.max(image[i:i+2, j:j+2])

print("\nMax Pooled Image:\n")
print(pooled)

Original Image:

[[250  11 157  61 127  16]
 [250 199  12 209  70 163]
 [172   5  76 205 255 207]
 [ 18 243 171 105 234  59]
 [ 13 250 141  80 116 158]
 [254 186 219 132 217  30]]

Max Pooled Image:

[[250 209 163]
 [243 205 255]
 [254 219 217]]


In [2]:
import numpy as np

def average_pooling_2x2(image):
    rows, cols = image.shape

    output = np.zeros((rows//2, cols//2))

    for i in range(0, rows, 2):
        for j in range(0, cols, 2):
            region = image[i:i+2, j:j+2]
            output[i//2, j//2] = np.mean(region)

    return output

# Example Image
image = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,100,110,120],
    [130,140,150,160]
])

print("Original Image:\n")
print(image)

print("\nAverage Pooled Image:\n")
print(average_pooling_2x2(image))

Original Image:

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]

Average Pooled Image:

[[ 35.  55.]
 [115. 135.]]


In [3]:
import numpy as np

feature_map = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])

print("Feature Map:\n")
print(feature_map)

max_pool = np.zeros((2,2), dtype=int)
avg_pool = np.zeros((2,2))

for i in range(0,4,2):
    for j in range(0,4,2):

        block = feature_map[i:i+2, j:j+2]

        max_pool[i//2, j//2] = np.max(block)
        avg_pool[i//2, j//2] = np.mean(block)

print("\nMax Pooling Result:\n")
print(max_pool)

print("\nAverage Pooling Result:\n")
print(avg_pool)

print("\nObservation:")
print("Average pooling keeps more overall information, while max pooling keeps only the strongest feature from each region.")

Feature Map:

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Max Pooling Result:

[[ 6  8]
 [14 16]]

Average Pooling Result:

[[ 3.5  5.5]
 [11.5 13.5]]

Observation:
Average pooling keeps more overall information, while max pooling keeps only the strongest feature from each region.


In [4]:
import numpy as np

# Input Image
image = np.array([
    [1,2,3,0,1],
    [4,5,6,1,2],
    [7,8,9,2,3],
    [1,2,3,4,5],
    [6,7,8,9,0]
])

print("Input Image:\n")
print(image)

# Edge Detection Filter
kernel = np.array([
    [1,0,-1],
    [1,0,-1],
    [1,0,-1]
])

# Convolution
conv_output = np.zeros((3,3))

for i in range(3):
    for j in range(3):
        region = image[i:i+3, j:j+3]
        conv_output[i,j] = np.sum(region * kernel)

print("\nConvolution Output:\n")
print(conv_output)

# Max Pooling (2x2)
pool_output = np.zeros((1,1))

pool_output[0,0] = np.max(conv_output[0:2,0:2])

print("\nMax Pooling Output:\n")
print(pool_output)

Input Image:

[[1 2 3 0 1]
 [4 5 6 1 2]
 [7 8 9 2 3]
 [1 2 3 4 5]
 [6 7 8 9 0]]

Convolution Output:

[[-6. 12. 12.]
 [-6.  8.  8.]
 [-6.  2. 12.]]

Max Pooling Output:

[[12.]]


In [5]:
print("Pooling Layers in CNNs\n")

print("Example: Instagram")
print("Instagram uses CNNs to recognize faces and objects in photos.")
print("Pooling reduces the size of feature maps while keeping the most important features.")
print("This allows the model to process images faster and recognize faces even when they appear at different positions.")

print("\nExample: Zomato")
print("Zomato can identify food items such as pizza or burgers from uploaded images.")
print("Pooling removes unnecessary details and keeps the important food features, making predictions faster and more accurate.")

Pooling Layers in CNNs

Example: Instagram
Instagram uses CNNs to recognize faces and objects in photos.
Pooling reduces the size of feature maps while keeping the most important features.
This allows the model to process images faster and recognize faces even when they appear at different positions.

Example: Zomato
Zomato can identify food items such as pizza or burgers from uploaded images.
Pooling removes unnecessary details and keeps the important food features, making predictions faster and more accurate.
